local irrlicht = {}

irrlicht.E_DRIVER_TYPE = {
    EDT_NULL = 0,
    EDT_SOFTWARE = 1,
    EDT_BURNINGSVIDEO = 2,
    EDT_DIRECT3D8 = 3,
    EDT_DIRECT3D9 = 4,
    EDT_OPENGL = 5,
    EDT_COUNT = 6
}

irrlicht.E_ANTI_ALIASING_MODE = {
    EAAM_OFF = 0,
    EAAM_SIMPLE = 1,
    EAAM_QUALITY = 2,
    EAAM_LINE_SMOOTH = 3,
    EAAM_POINT_SMOOTH = 4,
    EAAM_FULL_BASIC = 5,
    EAAM_ALPHA_TO_COVERAGE = 6
}

irrlicht.E_BLEND_OPERATION = {
    EBO_NONE = 0,
    EBO_ADD = 1,
    EBO_SUBTRACT = 2,
    EBO_REVSUBTRACT = 3,
    EBO_MIN = 4,
    EBO_MAX = 5,
    EBO_MIN_FACTOR = 6,
    EBO_MAX_FACTOR = 7,
    EBO_MIN_ALPHA = 8,
    EBO_MAX_ALPHA = 9
}

irrlicht.E_COLOR_MATERIAL = {
    ECM_NONE = 0,
    ECM_DIFFUSE = 1,
    ECM_AMBIENT = 2,
    ECM_EMISSIVE = 3,
    ECM_SPECULAR = 4,
    ECM_DIFFUSE_AND_AMBIENT = 5
}

irrlicht.E_COLOR_PLANE = {
    ECP_NONE = 0,
    ECP_ALPHA = 1,
    ECP_RED = 2,
    ECP_GREEN = 3,
    ECP_BLUE = 4,
    ECP_RGB = 5,
    ECP_ALL = 6
}

irrlicht.E_COMPARISON_FUNC = {
    ECFN_NEVER = 0,
    ECFN_LESSEQUAL = 1,
    ECFN_EQUAL = 2,
    ECFN_NOTEQUAL = 3,
    ECFN_GREATEREQUAL = 4,
    ECFN_GREATER = 5,
    ECFN_ALWAYS = 6
}

irrlicht.E_FOG_TYPE = {
    EFT_FOG_EXP = 0,
    EFT_FOG_LINEAR = 1,
    EFT_FOG_EXP2 = 2
}

irrlicht.E_LIGHT_TYPE = {
    ELT_POINT = 0,
    ELT_SPOT = 1,
    ELT_DIRECTIONAL = 2
}

irrlicht.E_MATERIAL_TYPE = {
    EMT_SOLID = 0,
    EMT_SOLID_2_LAYER = 1,
    EMT_LIGHTMAP = 2,
    EMT_LIGHTMAP_ADD = 3,
    EMT_LIGHTMAP_M2 = 4,
    EMT_LIGHTMAP_M4 = 5,
    EMT_LIGHTMAP_LIGHTING = 6,
    EMT_LIGHTMAP_LIGHTING_M2 = 7,
    EMT_LIGHTMAP_LIGHTING_M4 = 8,
    EMT_DETAIL_MAP = 9,
    EMT_SPHERE_MAP = 10,
    EMT_REFLECTION_2_LAYER = 11,
    EMT_TRANSPARENT_ADD_COLOR = 12,
    EMT_TRANSPARENT_ALPHA_CHANNEL = 13,
    EMT_TRANSPARENT_ALPHA_CHANNEL_REF = 14,
    EMT_TRANSPARENT_VERTEX_ALPHA = 15,
    EMT_TRANSPARENT_REFLECTION_2_LAYER = 16,
    EMT_NORMAL_MAP_SOLID = 17,
    EMT_NORMAL_MAP_TRANSPARENT_ADD_COLOR = 18,
    EMT_NORMAL_MAP_TRANSPARENT_VERTEX_ALPHA = 19,
    EMT_PARALLAX_MAP_SOLID = 20,
    EMT_PARALLAX_MAP_TRANSPARENT_ADD_COLOR = 21,
    EMT_PARALLAX_MAP_TRANSPARENT_VERTEX_ALPHA = 22,
    EMT_ONETEXTURE_BLEND = 23,
    EMT_FORCE_32BIT = 24
}

irrlicht.E_MATERIAL_FLAG = {
    EMF_WIREFRAME = 0,
    EMF_POINTCLOUD = 1,
    EMF_GOURAUD_SHADING = 2,
    EMF_LIGHTING = 3,
    EMF_ZBUFFER = 4,
    EMF_ZWRITE_ENABLE = 5,
    EMF_BACK_FACE_CULLING = 6,
    EMF_FRONT_FACE_CULLING = 7,
    EMF_BILINEAR_FILTER = 8,
    EMF_TRILINEAR_FILTER = 9,
    EMF_ANISOTROPIC_FILTER = 10,
    EMF_FOG_ENABLE = 11,
    EMF_NORMALIZE_NORMALS = 12,
    EMF_TEXTURE_WRAP = 13,
    EMF_ANTI_ALIASING = 14,
    EMF_COLOR_MASK = 15,
    EMF_COLOR_MATERIAL = 16,
    EMF_USE_MIP_MAPS = 17,
    EMF_BLEND_OPERATION = 18,
    EMF_POLYGON_OFFSET = 19
}

irrlicht.E_POLYGON_OFFSET = {
    EPO_BACK = 0,
    EPO_FRONT = 1
}

irrlicht.E_RENDER_TARGET = {
    ERT_FRAME_BUFFER = 0,
    ERT_RENDER_TEXTURE = 1,
    ERT_MULTI_RENDER_TEXTURES = 2,
    ERT_STEREO_LEFT_BUFFER = 3,
    ERT_STEREO_RIGHT_BUFFER = 4,
    ERT_STEREO_BOTH_BUFFERS = 5,
    ERT_AUX_BUFFER0 = 6,
    ERT_AUX_BUFFER1 = 7,
    ERT_AUX_BUFFER2 = 8,
    ERT_AUX_BUFFER3 = 9,
    ERT_AUX_BUFFER4 = 10
}

irrlicht.E_TEXTURE_CLAMP = {
    ETC_REPEAT = 0,
    ETC_CLAMP = 1,
    ETC_CLAMP_TO_EDGE = 2,
    ETC_CLAMP_TO_BORDER = 3,
    ETC_MIRROR = 4,
    ETC_MIRROR_CLAMP = 5,
    ETC_MIRROR_CLAMP_TO_EDGE = 6,
    ETC_MIRROR_CLAMP_TO_BORDER = 7
}

irrlicht.E_TEXTURE_CREATION_FLAG = {
    ETCF_ALWAYS_16_BIT = 0,
    ETCF_ALWAYS_32_BIT = 1,
    ETCF_OPTIMIZED_FOR_QUALITY = 2,
    ETCF_OPTIMIZED_FOR_SPEED = 3,
    ETCF_CREATE_MIP_MAPS = 4,
    ETCF_NO_ALPHA_CHANNEL = 5,
    ETCF_ALLOW_NON_POWER_2 = 6
}



return irrlicht