local irrlicht = {}

irrlicht.DRIVER_TYPE = {
    EDT_NULL = 0,
    EDT_SOFTWARE = 1,
    EDT_BURNINGSVIDEO = 2,
    EDT_DIRECT3D8 = 3,
    EDT_DIRECT3D9 = 4,
    EDT_OPENGL = 5,
    EDT_COUNT = 6
}

irrlicht.ANTI_ALIASING_MODE = {
    EAAM_OFF = 0,
    EAAM_SIMPLE = 1,
    EAAM_QUALITY = 2,
    EAAM_LINE_SMOOTH = 3,
    EAAM_POINT_SMOOTH = 4,
    EAAM_FULL_BASIC = 5,
    EAAM_ALPHA_TO_COVERAGE = 6
}

irrlicht.BLEND_OPERATION = {
    EBO_NONE = 0,
    EBO_ADD = 1,
    EBO_SUBTRACT = 2,
    EBO_REVSUBTRACT = 3,
    EBO_MIN = 4,
    EBO_MAX = 5,
    EBO_MIN_FACTOR = 6,
    EBO_MAX_FACTOR = 7,
    EBO_MIN_ALPHA = 8,
    EBO_MAX_ALPHA = 9
}

irrlicht.COLOR_MATERIAL = {
    ECM_NONE = 0,
    ECM_DIFFUSE = 1,
    ECM_AMBIENT = 2,
    ECM_EMISSIVE = 3,
    ECM_SPECULAR = 4,
    ECM_DIFFUSE_AND_AMBIENT = 5
}

irrlicht.COLOR_PLANE = {
    ECP_NONE = 0,
    ECP_ALPHA = 1,
    ECP_RED = 2,
    ECP_GREEN = 3,
    ECP_BLUE = 4,
    ECP_RGB = 5,
    ECP_ALL = 6
}

irrlicht.COMPARISON_FUNC = {
    ECFN_NEVER = 0,
    ECFN_LESSEQUAL = 1,
    ECFN_EQUAL = 2,
    ECFN_NOTEQUAL = 3,
    ECFN_GREATEREQUAL = 4,
    ECFN_GREATER = 5,
    ECFN_ALWAYS = 6
}

irrlicht.FOG_TYPE = {
    EFT_FOG_EXP = 0,
    EFT_FOG_LINEAR = 1,
    EFT_FOG_EXP2 = 2
}

irrlicht.LIGHT_TYPE = {
    ELT_POINT = 0,
    ELT_SPOT = 1,
    ELT_DIRECTIONAL = 2
}

irrlicht.MATERIAL_TYPE = {
    EMT_SOLID = 0,
    EMT_SOLID_2_LAYER = 1,
    EMT_LIGHTMAP = 2,
    EMT_LIGHTMAP_ADD = 3,
    EMT_LIGHTMAP_M2 = 4,
    EMT_LIGHTMAP_M4 = 5,
    EMT_LIGHTMAP_LIGHTING = 6,
    EMT_LIGHTMAP_LIGHTING_M2 = 7,
    EMT_LIGHTMAP_LIGHTING_M4 = 8,
    EMT_DETAIL_MAP = 9,
    EMT_SPHERE_MAP = 10,
    EMT_REFLECTION_2_LAYER = 11,
    EMT_TRANSPARENT_ADD_COLOR = 12,
    EMT_TRANSPARENT_ALPHA_CHANNEL = 13,
    EMT_TRANSPARENT_ALPHA_CHANNEL_REF = 14,
    EMT_TRANSPARENT_VERTEX_ALPHA = 15,
    EMT_TRANSPARENT_REFLECTION_2_LAYER = 16,
    EMT_NORMAL_MAP_SOLID = 17,
    EMT_NORMAL_MAP_TRANSPARENT_ADD_COLOR = 18,
    EMT_NORMAL_MAP_TRANSPARENT_VERTEX_ALPHA = 19,
    EMT_PARALLAX_MAP_SOLID = 20,
    EMT_PARALLAX_MAP_TRANSPARENT_ADD_COLOR = 21,
    EMT_PARALLAX_MAP_TRANSPARENT_VERTEX_ALPHA = 22,
    EMT_ONETEXTURE_BLEND = 23,
    EMT_FORCE_32BIT = 24
}

irrlicht.MATERIAL_FLAG = {
    EMF_WIREFRAME = 0,
    EMF_POINTCLOUD = 1,
    EMF_GOURAUD_SHADING = 2,
    EMF_LIGHTING = 3,
    EMF_ZBUFFER = 4,
    EMF_ZWRITE_ENABLE = 5,
    EMF_BACK_FACE_CULLING = 6,
    EMF_FRONT_FACE_CULLING = 7,
    EMF_BILINEAR_FILTER = 8,
    EMF_TRILINEAR_FILTER = 9,
    EMF_ANISOTROPIC_FILTER = 10,
    EMF_FOG_ENABLE = 11,
    EMF_NORMALIZE_NORMALS = 12,
    EMF_TEXTURE_WRAP = 13,
    EMF_ANTI_ALIASING = 14,
    EMF_COLOR_MASK = 15,
    EMF_COLOR_MATERIAL = 16,
    EMF_USE_MIP_MAPS = 17,
    EMF_BLEND_OPERATION = 18,
    EMF_POLYGON_OFFSET = 19
}

irrlicht.POLYGON_OFFSET = {
    EPO_BACK = 0,
    EPO_FRONT = 1
}

irrlicht.RENDER_TARGET = {
    ERT_FRAME_BUFFER = 0,
    ERT_RENDER_TEXTURE = 1,
    ERT_MULTI_RENDER_TEXTURES = 2,
    ERT_STEREO_LEFT_BUFFER = 3,
    ERT_STEREO_RIGHT_BUFFER = 4,
    ERT_STEREO_BOTH_BUFFERS = 5,
    ERT_AUX_BUFFER0 = 6,
    ERT_AUX_BUFFER1 = 7,
    ERT_AUX_BUFFER2 = 8,
    ERT_AUX_BUFFER3 = 9,
    ERT_AUX_BUFFER4 = 10
}

irrlicht.TEXTURE_CLAMP = {
    ETC_REPEAT = 0,
    ETC_CLAMP = 1,
    ETC_CLAMP_TO_EDGE = 2,
    ETC_CLAMP_TO_BORDER = 3,
    ETC_MIRROR = 4,
    ETC_MIRROR_CLAMP = 5,
    ETC_MIRROR_CLAMP_TO_EDGE = 6,
    ETC_MIRROR_CLAMP_TO_BORDER = 7
}

irrlicht.TEXTURE_CREATION_FLAG = {
    ETCF_ALWAYS_16_BIT = 0,
    ETCF_ALWAYS_32_BIT = 1,
    ETCF_OPTIMIZED_FOR_QUALITY = 2,
    ETCF_OPTIMIZED_FOR_SPEED = 3,
    ETCF_CREATE_MIP_MAPS = 4,
    ETCF_NO_ALPHA_CHANNEL = 5,
    ETCF_ALLOW_NON_POWER_2 = 6
}

irrlicht.KEY_CODE = {
    KEY_LBUTTON = 0,
    KEY_RBUTTON = 1,
    KEY_CANCEL = 2,
    KEY_MBUTTON = 3,
    KEY_XBUTTON1 = 4,
    KEY_XBUTTON2 = 5,
    KEY_BACK = 8,
    KEY_TAB = 9,
    KEY_CLEAR = 12,
    KEY_RETURN = 13,
    KEY_SHIFT = 16,
    KEY_CONTROL = 17,
    KEY_MENU = 18,
    KEY_PAUSE = 19,
    KEY_CAPITAL = 20,
    KEY_KANA = 21,
    KEY_HANGUEL = 21,
    KEY_HANGUL = 21,
    KEY_JUNJA = 23,
    KEY_FINAL = 24,
    KEY_HANJA = 25,
    KEY_KANJI = 25,
    KEY_ESCAPE = 27,
    KEY_CONVERT = 28,
    KEY_NONCONVERT = 29,
    KEY_ACCEPT = 30,
    KEY_MODECHANGE = 31,
    KEY_SPACE = 32,
    KEY_PRIOR = 33,
    KEY_NEXT = 34,
    KEY_END = 35,
    KEY_HOME = 36,
    KEY_LEFT = 37,
    KEY_UP = 38,
    KEY_RIGHT = 39,
    KEY_DOWN = 40,
    KEY_SELECT = 41,
    KEY_PRINT = 42,
    KEY_EXECUT = 43,
    KEY_SNAPSHOT = 44,
    KEY_INSERT = 45,
    KEY_DELETE = 46,
    KEY_HELP = 47,
    KEY_KEY_0 = 48,
    KEY_KEY_1 = 49,
    KEY_KEY_2 = 50,
    KEY_KEY_3 = 51,
    KEY_KEY_4 = 52,
    KEY_KEY_5 = 53,
    KEY_KEY_6 = 54,
    KEY_KEY_7 = 55,
    KEY_KEY_8 = 56,
    KEY_KEY_9 = 57,
    KEY_KEY_A = 65,
    KEY_KEY_B = 66,
    KEY_KEY_C = 67,
    KEY_KEY_D = 68,
    KEY_KEY_E = 69,
    KEY_KEY_F = 70,
    KEY_KEY_G = 71,
    KEY_KEY_H = 72,
    KEY_KEY_I = 73,
    KEY_KEY_J = 74,
    KEY_KEY_K = 75,
    KEY_KEY_L = 76,
    KEY_KEY_M = 77,
    KEY_KEY_N = 78,
    KEY_KEY_O = 79,
    KEY_KEY_P = 80,
    KEY_KEY_Q = 81,
    KEY_KEY_R = 82,
    KEY_KEY_S = 83,
    KEY_KEY_T = 84,
    KEY_KEY_U = 85,
    KEY_KEY_V = 86,
    KEY_KEY_W = 87,
    KEY_KEY_X = 88,
    KEY_KEY_Y = 89,
    KEY_KEY_Z = 90,
    KEY_LWIN = 91,
    KEY_RWIN = 92,
    KEY_APPS = 93,
    KEY_SLEEP = 95,
    KEY_NUMPAD0 = 96,
    KEY_NUMPAD1 = 97,
    KEY_NUMPAD2 = 98,
    KEY_NUMPAD3 = 99,
    KEY_NUMPAD4 = 100,
    KEY_NUMPAD5 = 101,
    KEY_NUMPAD6 = 102,
    KEY_NUMPAD7 = 103,
    KEY_NUMPAD8 = 104,
    KEY_NUMPAD9 = 105,
    KEY_MULTIPLY = 106,
    KEY_ADD = 107,
    KEY_SEPARATOR = 108,
    KEY_SUBTRACT = 109,
    KEY_DECIMAL = 110,
    KEY_DIVIDE = 111,
    KEY_F1 = 112,
    KEY_F2 = 113,
    KEY_F3 = 114,
    KEY_F4 = 115,
    KEY_F5 = 116,
    KEY_F6 = 117,
    KEY_F7 = 118,
    KEY_F8 = 119,
    KEY_F9 = 120,
    KEY_F10 = 121,
    KEY_F11 = 122,
    KEY_F12 = 123,
    KEY_NUMLOCK = 144,
    KEY_SCROLL = 145,
    KEY_LSHIFT = 160,
    KEY_RSHIFT = 161,
    KEY_LCONTROL = 162,
    KEY_RCONTROL = 163,
    KEY_LMENU = 164,
    KEY_RMENU = 165,
    KEY_OEM_1 = 186,
    KEY_PLUS = 187,
    KEY_COMMA = 188,
    KEY_MINUS = 189,
    KEY_PERIOD = 190,
    KEY_OEM_2 = 191,
    KEY_OEM_3 = 192,
    KEY_OEM_4 = 219,
    KEY_OEM_5 = 220,
    KEY_OEM_6 = 221,
    KEY_OEM_7 = 222,
    KEY_OEM_8 = 223,
    KEY_OEM_AX = 225,
    KEY_OEM_102 = 226,
    KEY_ATTN = 246,
    KEY_CRSEL = 247,
    KEY_EXSEL = 248,
    KEY_EREOF = 249,
    KEY_PLAY = 250,
    KEY_ZOOM = 251,
    KEY_PA1 = 252,
    KEY_OEM_CLEAR = 254,
    KEY_KEY_CODES_COUNT = 255
}

irrlicht.SOUND_EFFECT = {
    DISTORTION = 0,
    ECHO = 1,
    REVERB = 2,
    COMPRESSOR = 3
}


return irrlicht